# Generated by Django 6.0.1 on 2026-01-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(blank=True, default='default_cover.png', upload_to='covers/'),
        ),
    ]
