# Generated by Django 6.0.1 on 2026-01-20 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_post_image_post_repost_of_post_video_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
    ]
